FIND_PATH(FREEGLUT_INCLUDE_DIR GL/glut.h
	  PATHS 
                "${CMAKE_SOURCE_DIR}/freeglut/include"

                )
# MESSAGE(${CMAKE_SOURCE_DIR})
SET(SEARCH_PATHS
    "${FREEGLUT_INCLUDE_DIR}/../lib")
FIND_LIBRARY(FREEGLUT_LIBRARY NAMES freeglut PATHS ${SEARCH_PATHS})

INCLUDE (FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(FreeGLUT DEFAULT_MSG FREEGLUT_LIBRARY  FREEGLUT_INCLUDE_DIR)

IF (FREEGLUT_FOUND)
   SET(FREEGLUT_LIBRARY "${FREEGLUT_LIBRARY}")
   SET(FREEGLUT_INCLUDE_DIR "${FREEGLUT_INCLUDE_DIR}")
ENDIF (FREEGLUT_FOUND)
